FROM node:20-alpine

WORKDIR /app

# 의존성 설치 및 개발 서버 실행을 위한 시작 스크립트 추가
COPY docker-entrypoint-dev.sh /
RUN chmod +x /docker-entrypoint-dev.sh

EXPOSE 3000

# 시작 스크립트를 엔트리포인트로 사용
ENTRYPOINT ["/docker-entrypoint-dev.sh"]