version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: lyckabc.xyz/registry/gopediafe:dev
    container_name: gopediafe-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules_volume:/app/node_modules
    environment:
      - NODE_ENV=development
      # - VITE_API_URL=${VITE_API_URL}
      # - VITE_BACKEND_API_VERSION=${VITE_BACKEND_API_VERSION}
    networks:
      - gopedia-network
    extra_hosts:
      - "registry-server:172.17.0.1"
      
volumes:
node_modules_volume:

  prod:
    build:
      context: .
      dockerfile: Dockerfile
      # args:
      #   - VITE_API_URL=${VITE_API_URL}
      #   - VITE_BACKEND_API_VERSION=${VITE_BACKEND_API_VERSION}
    image: lyckabc.xyz/registry/gopediafe:prod
    container_name: gopediafe-prod
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - gopedia-network
    extra_hosts:
      - "registry-server:172.17.0.1"

networks:
  gopedia-network:
    driver: bridge
